ref_validation: # use ref data : ref data
    FieldObjectGrowth.FieldObjectID:        FieldObject.ID
    MonsterSpawn.MonsterID:                 Monster.ID
    MonsterSpawn.SpawnGroupID:              MonsterSpawnGroup.ID
    FieldTile.FieldGroupID:                 FieldGroup.ID


value_size_compare: # big value : small value
    FieldObjectGrowth.PhysicDamage_Max:     FieldObjectGrowth.PhysicDamage_Min